config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 # resources :users
  resources :profiles  do 

    resources :experiences
  end
  
  
  root to: "profiles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    belongs_to :user
    belongs_to :profile
  end
  

app/models/profile.rb
class Profile < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    belongs_to :user
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :profiles
  has_many :experiences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #  before_action :authenticate_user!
    protect_from_forgery with: :exception
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

    def index
        @experiences = Experience.all
    end

    def new
        @experience = Experience.new
        @profile = Profile.find(params[:profile_id])
    end
    
    def show
        @experience = Experience.find(params[:id])
    end
    def create
        @experience = Experience.new(experience_params)
        @experience.user_id = current_user.id
        @experience.profile_id = params[:profile_id]
       
        if @experience.save
            flash[:success] = "Object successfully created"
            redirect_to "/profiles/#{params[:profile_id]}/experiences/#{@experiences.id}"
        else
            redirect_back(fallback_location: "/")
            flash[:alert] = "not created"
           # redirect_to "/"
        end
    end

    private

    def experience_params 
        params.require(:experience).permit(:title, :industry, :start_date, :end_date, :actually, :user_id, :description)
    end

    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def index
        @profiles = Profile.all
    end

    def new
        @profile = Profile.new
    end
    
    def show
        @profile = Profile.find(params[:id])
    end
    def create
        @profile = current_user.profiles.new

        if @profile.save
            flash[:success] = "Object successfully created"
        else
            redirect_to "/profiles"
        end
    end

    def destroy
        @profile = Profile.find(params[:id])
        if @profile.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to "/profiles"
        else
            flash[:error] = 'Something went wrong'
            redirect_to "/profiles"
        end
    end

    def edit
        @profile = Profile.find(params[:id])
    end

    def update
        @profile = Profile.find(params[:id])
        if @profile.update_attributes(params[:profile_params])
          flash[:success] = "Object was successfully updated"
          redirect_to "/profiles/#{:id}/edit"
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end
    
    
    

    private

    def profile_params
        params.require(:profile).permit(:user_id)
    end

    
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    # if super.save
    #   flash[:success] = "Object successfully created"
    #   redirect_to "/profiles/new"
    # else
    #     redirect_to "/profiles"
    # end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profession, :summary, :image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profession, :summary, :image])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/experiences/index.html.erb
<% @profile.experiences.each do |experience| %>

<p>
    <div>
        <label> Title:  </label>
        <%= experience.title%>
    </div>

    <div>
        <label> Industry:  </label>
        <%= experience.industry%>
    </div>

    <div>
        <label> Description:  </label>
        <%= experience.description%>
    </div>
    <div>
        <label> start date:  </label>
        <%= experience.start_date%>
    </div>

    <div>
        <label> end date:  </label>
        <%= experience.end_date%>
    </div>
</p>

<% end %>

app/views/experiences/new.html.erb
<%= form_for [@profile,@experience] do |form | %>

    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder:"title" %>
    </div>
    
    <div class="field">
    <%= form.label :industry %>
    <%= form.text_field :industry, placeholder:"industry" %>
    </div>
      <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, placeholder:"description" %>
    </div>
 
    <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, placeholder:"start date" %>
    </div> 

    <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :start_date, placeholder:"end date" %>
    </div> 

    <div class="actions">
    <%= form.submit %>
    </div>
<%end%>

app/views/experiences/show.html.erb
hola

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>One Page Wonder - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/css/one-page-wonder.min.css" rel="stylesheet">
 
 <!-- NOTICE notify login and logout -->
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
   <p class="alert alert-danger"><%= alert %></p>
  <% end %>


  </head>

  <body>
   <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom navbar-fixed-top">
    <div class="container">
      <% if user_signed_in? %>
        <a class="navbar-brand" href="#">hello <%= current_user.name %> </a>
      <% else %>
        <a class="navbar-brand" href="#">hello </a>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Account login settings', edit_user_registration_path, :class => 'navbar-brand' %>
              <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :class => 'navbar-brand' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-brand'  %>
              <%= link_to "Login", new_user_session_path, :class => 'navbar-brand'  %> 
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

    <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Share Easy Resume</h1>
        <h2 class="masthead-subheading mb-0">Find Quickly New Oportunities</h2>
        <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">Learn More</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>



    


   
    <%= yield %>


  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/vendor/jquery/jquery.min.js"></script>
  <script src="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/profiles/edit.html.erb
<h2>Profile </h2>


<%= form_with model: @user do |f| %>
    <div>
        <%= image_tag(@profile.user.image, style: "width: 100px") %>
    </div>

    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, placeholder: "#{@profile.user.name}" %>
    </div>

    <div class="field">
        <%= f.label :profession %><br />
        <%= f.text_field :profession, autofocus: true, autocomplete: "profession", placeholder: "#{@profile.user.profession}" %>
    </div>

    <div class="field">
        <%= f.label :summary %><br />
        <%= f.text_area :summary, autofocus: true, autocomplete: "summary", placeholder: "#{@profile.user.summary}" %>
    </div>

    <div class="field">
        <p> 
            <%= f.label :image %>
            <%= f.file_field :image %>
        </p>
    </div>


    <div class="actions">
        <%= f.submit "Update" %>
    </div>
<% end %>


<%= link_to "Back", :back %>

app/views/profiles/index.html.erb
<p>
    <% @profiles.each do |profile| %>
      <section>
        <div class="container">
          <div class="row align-items-center">
            <div class="row text-center">
                    <div class="card h-100">
                <div class="col-lg-3 col-md-6 mb-4">
                      <%= image_tag(profile.user.image, class:"card-img-top", width:"500px" ) %>
                      <div class="card-body">
                        <h4 class="card-title">  <p><%= profile.user.name%></p></h4>
                        <p class="card-text"> <p><%= profile.user.summary%></p> </p>
                      </div>
                      <div class="card-footer">
                          <div>
                            <h4 class="card-title"> <%= profile.user.profession%></h4>
                          </div>
                        <a><%= link_to 'More details', profile, class:"btn btn-primary" %></a>
                      </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </section>
    <% end %>
</p>

app/views/profiles/new.html.erb
<%= form_with model: @profile do |form| %>

    <div class="actions">
    <%= form.submit %>
    </div>
<%end%>

app/views/profiles/show.html.erb
<div>
        <%= image_tag(@profile.user.image, style: "width: 100px") %>
</div>

<div>
        <label> Name:  </label>
        <%= @profile.user.name %>
</div>

<div>
        <label> Profession:  </label>
        <%= @profile.user.profession %>
</div>

<div>
        <label> Summary:  </label>
        <%= @profile.user.summary %>
</div>

<% if user_signed_in? && current_user.id == @profile.user.id %>
        <%= link_to "Edit", "/profiles/#{@profile.id}/edit", method: :post %>
        <%= link_to "Delete", @profile, method: :delete %>
        <%= link_to 'Back', profiles_path %>
        <% current_user %>
        <% elsif user_signed_in? %>
                <%= link_to 'Back', "/" %>
        <% elsif %>
        <%= link_to "Sign up", new_user_registration_path %> 
        <%= link_to "Login", new_user_session_path %>
    
<% end %>


<h1> Experiences </h1>
<p><% if user_signed_in? && current_user.id == @profile.user.id %>
        <%= link_to "Add experience", "/profiles/#{params[:id]}/experiences/new", method: :post %>
<% end %></p>
<table>
  <thead style= text-align:center;>
  
    <tr>
      <th>Title</th>
      <th>Industry</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Actually?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody style= text-align:center;>
    <% @profile.experiences.each do |report| %>
      <tr>
        <td><%= report.title%></td>
        <td><%= report.industry %></td>
        <td><%= report.description %></td>
        <td><%= report.start_date%></td>
        <td><%= report.end_date %></td>
        <td><%= report.actually %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
hola

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>